### ISSUE TITLE
#1 UI Challenge - Story

### ISSUE THREAD

**Issue by dehamzah** [flutter-jakarta/flutter-ui-challenge#1]
## Topic

Our first ui challenge is creating a **Story**.

You can mimic the story Snapchat, Instagram, WhatsApp, Facebook, or you can create your own story design.

## Time Limit

You must finish this before **5 July 2020**. Just submit what you can do even though its not perfect.

## Registration and Submission

Comment first in this issue to secure your spots. After you finish the challenge, edit it with the following template:

- Name
- Twitter
- App Name (ex. Instagram Story)
- Demo Gif (Record your live app and convert it to gif, you can use 3rd party service like [ezgif.com](https://ezgif.com/video-to-gif)
- Public repository url

## Share Your Progress

Every participant is encouraged to share their progress in Twitter. Record your progress and share it with hashtag **#FlutterJakartaUIChallenge #FlutterJakartaUIChallenge1**

## Prize

The best submitter from Indonesia will receive swag as a reward for their efforts. (TBA)

## Learn Together

If you are new to flutter or stuck in the implementation, feel free to reach us in [Telegram](https://t.me/flutter_jkt), we plan to do live coding session every week to create this ui challenge.

----

## Example

Name: Dede Hamzah
Twitter: https://twitter.com/dehamzah
App Name: Instagram Story
Demo:
![instagram-story](https://user-images.githubusercontent.com/6959476/84641717-a4196580-af25-11ea-93e4-d38c78ff7771.gif)
Repository: https://github.com/dehamzah/instagram-story (example)

**Comment by zae1403** [comment]
Up

**Comment by jfushada** [comment]
Me~

**Comment by albertusdev** [comment]
Up up up

**Comment by leonardovinsen** [comment]
RSVP dulu

**Comment by rrifafauzikomara** [comment]
Otw~

**Comment by ilhamalamsyh** [comment]
Up

**Comment by atprastyo** [comment]
toktok
